# Generated by Django 3.2 on 2022-02-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_category_prodcut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
